SRC_SUB += $(TFTP_BOOT_DIR)/tftp_main.c
SRC_SUB += $(TFTP_BOOT_DIR)/net.c
SRC_SUB += $(TFTP_BOOT_DIR)/tftp.c
SRC_SUB += $(TFTP_BOOT_DIR)/validate.c
SRC_SUB += $(TFTP_BOOT_DIR)/debug.c
SRC_SUB += $(TFTP_BOOT_DIR)/ihex.c